# Generated by Django 2.0.4 on 2018-11-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='closing_time',
            field=models.TimeField(default='01:45:33'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='opening_time',
            field=models.TimeField(default='01:45:33'),
        ),
    ]
